version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    environment:
      # Coolify typically injects PORT; default kept for local runs
      PORT: ${PORT:-3000}
      # These are runtime copies (not used by the SPA after build),
      # but kept for clarity/debug
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    # For local testing; in Coolify, you can omit and set the internal port to 3000 in the UI
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:${PORT:-3000}/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    restart: unless-stopped
